# Site settings
title: Eduardo Donoso
email: eduardo@soijen.com
description: Eduardo Donoso - freelance travel writer
lang: ["en", "es"]
url: "https://edonoso.com"
author: Eduardo Donoso
twitter_username: edodonoso
facebook_username: eduardodonoso31
instagram_username: edopatagonia
linkedin_username: eduardo-donoso-21aa29111
google_analytics_key: UA-121436811-1
google_site_verification: 6xkhDJkFA_4txjLgKTqfBaguxFnWLw4Her7_zB8CIuw
permalink: /:title/

# Build settings
include: ["_pages"]

collections:
  portfolio:
    output: false

defaults:
  #languages
  -
    scope:
      path: "en"
    values:
      lang: "en"
      baseurl: ""
  -
    scope:
      path: "es"
    values:
      lang: "es"
      baseurl: "/es/"

#prose.io settings
prose:
  rooturl: ''
  siteurl: 'https://edonoso.com'
  media: '/assets/images'
  ignore:
    - _config.yml
    - /_layouts
    - /_includes
    - .gitignore
    - robots.txt
    - sitemap.xml
    - CNAME
  metadata:
    "":
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element: "hidden"
          value: "Eduardo Donoso"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          placeholder: "Add post title here"
      - name: "description"
        field:
          label: "Description"
          element: "text"
          placeholder: "Add post description here"
      - name: "date"
        field:
          label: "date"
          element: "text"
          value: "CURRENT_DATETIME"
      - name: "postHero"
        field:
          label: "PostHero Link"
          element: "text"
          placeholder: "/assets/images/myphoto.jpg"
      - name: "permalink"
        field:
          label: "Permalink"
          element: "text"
          placeholder: "/la-mauricie-canoe-camping/"
      - name: "ref"
        field:
          label: "Language Ref"
          element: "text"
          placeholder: "la-mauricie-canoe-camping"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "sustainability"
              value: "sustainability"
            - name: "travels"
              value: "travels"
            - name: "camping"
              value: "camping"
            - name: "canoe"
              value: "canoe"
            - name: "canada"
              value: "canada"
            - name: "quebec"
              value: "quebec"
            - name: "local"
              value: "local"
            - name: "new-york"
              value: "new-york"
            - name: "trail-running"
              value: "trail-running"
            - name: "chile"
              value: "chile"
            - name: "running"
              value: "running"
            - name: "road-trip"
              value: "road-trip"
            - name: "vermont"
              value: "vermont"

#menu translations
t:
  en:
    home:
      name: "Home"
      url: "/"
    about:
      name: "CV"
      url: "/about/"
    portfolio:
      name: "Portfolio"
      url: "/portfolio/"
    blog:
      name: "Blog"
      url: "/blog/"
    contact:
      name: "Contact"
      url: "/#contact"
  es:
      home:
        name: "Inicio"
        url: "/es/"
      about:
        name: "CV"
        url: "/es/about/"
      portfolio:
        name: "Portafolio"
        url: "/es/portfolio/"
      blog:
        name: "Blog"
        url: "/es/blog/"
      contact:
        name: "Contacto"
        url: "/es/#contact"
